# https://docs.pyscript.net/2024.10.2/user-guide/configuration/
name = "pipdev"
description = "An interactive tool for developers to test defined specifiers for version handling."

packages = [
    "colorama>=0.4",
    "packaging>=23.0",
    "tabulate>=0.8",
]

[[fetch]]
files = ['__init__.py', 'pipdev.py']
from = 'pipdev'
to_folder = 'pipdev'
