name = "pip-dev"
description = "An interactive tool for testing Python version specifiers."

packages = [
    "colorama>=0.4",
    "packaging>=23.0",
    "tabulate>=0.8",
]

[[fetch]]
files = ['app.py']
from = 'pip_dev'
to_folder = 'pip_dev'
